sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Boiler Temperatur oben"
    id: Boiler_Temperatur_oben
    register_type: read
    address: 1630
    unit_of_measurement: "째C"
    device_class: "temperature"
    state_class: "measurement"
    value_type: U_WORD
    filters:
      - multiply: 0.5

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Boiler Pumpe Ansteuerung"
    id: Boiler_Pumpe_Ansteuerung
    register_type: read
    address: 1632
    unit_of_measurement: "%"
    value_type: U_WORD

number:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Boiler Gew체nschte Boilertemperatur"
    id: Boiler_Gewuenschte_Boilertemperatur
    address: 1631
    unit_of_measurement: "째C"
    value_type: U_WORD
    multiply: 2
    min_value: 10
    max_value: 100

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Boiler Nachladen, wenn Boilertemperatur unter"
    id: Boiler_Nachladen_wenn_Boilertemperatur_unter
    address: 1632
    unit_of_measurement: "째C"
    value_type: U_WORD
    multiply: 2
    min_value: 1
    max_value: 90

binary_sensor:
  - platform: template
    name: "Boiler Pumpe Ansteuerung AN AUS"
    id: Boiler_Pumpe_Ansteuerung_AN_AUS
    lambda: |-
      if (id(Boiler_Pumpe_Ansteuerung).state > 0) {
        return true;
      } else {
        return false;
      }
