sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Kesseltemperatur"
    id: Kesseltemperatur
    register_type: read
    address: 0
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    value_type: U_WORD
    filters:
      - multiply: 0.5

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Abgastemperatur"
    id: Abgastemperatur
    register_type: read
    address: 1
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Saugzug - Ansteuerung"
    id: Saugzug_Ansteuerung
    register_type: read
    address: 13
    unit_of_measurement: "%"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Saugzugdrehzahl"
    id: Saugzugdrehzahl
    register_type: read
    address: 6
    unit_of_measurement: "rpm"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Sauerstoffregler"
    id: Sauerstoffregler
    register_type: read
    address: 16
    unit_of_measurement: "%"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Restsauerstoffgehalt"
    id: Restsauerstoffgehalt
    register_type: read
    address: 3
    unit_of_measurement: "%"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1

  # - platform: modbus_controller
  #   modbus_controller_id: ${modbus_controller_id}
  #   name: "Rücklauffühler"
  #   id: Ruecklauffuehler
  #   register_type: read
  #   address: 9
  #   unit_of_measurement: "°C"
  #   device_class: "temperature"
  #   state_class: "measurement"
  #   value_type: U_WORD
  #   filters:
  #     - multiply: 0.5

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Primärluft"
    id: Primaerluft
    register_type: read
    address: 11
    unit_of_measurement: "%"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Sekundärluft"
    id: Sekundaerluft
    register_type: read
    address: 12
    unit_of_measurement: "%"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Betriebsstunden"
    id: Betriebsstunden
    register_type: read
    address: 20
    unit_of_measurement: "h"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Stunden seit letzter Wartung"
    id: Stunden_seit_letzter_Wartung
    register_type: read
    address: 55
    unit_of_measurement: "h"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Betriebsstunden in der Feuererhaltung"
    id: Betriebsstunden_in_der_Feuererhaltung
    register_type: read
    address: 24
    unit_of_measurement: "h"
    value_type: U_WORD
# binary_sensor:
#   - platform: template
#     name: "Kesselzustand Heizen"
#     id: Kesselzustand_Heizen
#     lambda: |-
#       if (id(Kesselzustand).state == "Heizen") {
#         return true;
#       } else {
#         return false;
#       }
