sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Temperatur des Zweitkessel "
    id: Temperatur_Zweitkessel
    register_type: read
    address: 500
    unit_of_measurement: "°C"
    value_type: S_WORD
    filters:
      - multiply: 0.5

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Zustand des Brennerrelais  AN AUS"
    id: Zustand_des_Brennerrelais_Zweitkessel
    register_type: read
    address: 501
    value_type: U_WORD
