sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Puffer 1 Temperatur oben"
    id: Puffer_1_Temperatur_oben
    register_type: read
    address: 2000
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    value_type: U_WORD
    filters:
      - multiply: 0.5

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Puffer 1 Temperatur mitte"
    id: Puffer_1_Temperatur_mitte
    register_type: read
    address: 2001
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    value_type: U_WORD
    filters:
      - multiply: 0.5

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Puffer 1 Temperatur unten"
    id: Puffer_1_Temperatur_unten
    register_type: read
    address: 2002
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    value_type: U_WORD
    filters:
      - multiply: 0.5

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Puffer 1 Ladezustand"
    id: Puffer_1_Ladezustand
    register_type: read
    address: 2006
    unit_of_measurement: "%"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Puffer 1 Pufferpumpen Ansteuerung"
    id: Puffer_1_Pufferpumpen_Ansteuerung
    register_type: read
    address: 2003
    unit_of_measurement: "%"
    value_type: U_WORD

binary_sensor:
  - platform: template
    name: "Puffer 1 Pufferpumpen Ansteuerung AN AUS"
    id: Puffer_1_Pufferpumpen_Ansteuerung_AN_AUS
    lambda: |-
      if (id(Puffer_1_Pufferpumpen_Ansteuerung).state > 0) {
        return true;
      } else {
        return false;
      }
